# -*- coding: utf-8 -*-
"""Conversions.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nt8lEb8jAU7kwKBB3HokB_O4hr0BObnx
"""

#Activity 6
#Exercise 1

class Conversions(object):
    def __init__(self,feet,inches,pounds,kilograms,kelvin,celcius,hours,minutes):
        self.feet=feet
        self.pounds=pounds
        self.kilograms=kilograms
        self.kelvin=kelvin
        self.celcius=celcius
        self.hours=hours
        self.minutes=minutes
        self.inches=inches
        
    #1.feet to meters    
    def feetToMeters(self,feet):
        return feet/3.2808
        
    #2.Inches to meters
    def inchesToMeters(self,inches):
        return inches*0.0254
    
    #3.Pounds to kilograms
    def poundsToKilograms(self,pounds):
        return pounds/2.2046
    
    #4.Kilograms to pounds
    def kilogramsTopounds(self,kilograms):
        return kilograms*2.2046
    
    #5.Kelvin to Celcius
    def kelvinToCelcius(self,kelvin):
        return kelvin-273.15
    
    #6.Celcius to kelvin
    def celciusToKelvin(self,celcius):
        return celcius+273.15
    
    #Hours to seconds
    def hoursToSeconds(self,hours):
        return hours*3600
    
    #Minutes to seconds
    def minutesToSeconds(self,minutes):
        return minutes/0.016667

